<?php defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

class Api extends REST_Controller {

	public function __construct()
	{
		parent::__construct();
		$this->load->model('timetable_model');
	}

	public function timetable_get()
	{
		$bid = $this->uri->segment(4);
		$timetable = $this->timetable_model->get_all();

		 if ($bid === NULL)
		        {
		            // Check if the timetable data store contains timetable (in case the database result returns NULL)
		            if ($timetable)
		            {
		                // Set the response and exit
		                $this->response($timetable, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
		            }
		            else
		            {
		                // Set the response and exit
		                $this->response([
		                    'status' => FALSE,
		                    'message' => 'No timetable were found'
		                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
		            }
		        }
		     // Find and return a single record for a particular timetables.

		$id = $this->timetable_model->get_by(array('id' => $bid));
		// var_dump($id);
        // $id = (int) $id;

        // Validate the id.
        if ($id <= 0)
        {
            // Invalid id, set the response and exit.
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // Get the timetables from the array, using the id as key for retreival.
        // Usually a model is to be used for this.

        $timetables = NULL;
        // var_dump($id);
        if (!empty($id))
        {
        foreach ($id as $key => $value)
            {
            	var_dump($value->$key);
                // if (isset($value->id) && $value->id === $id)
                // {
                //      $timetables = $value;
                //  }
        	}
        }
        if (!empty($timetables))
        {
            $this->set_response($timetables, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'timetable could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
	}

	public function timetable_post()
    {
        // $this->some_model->update_timetable( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function timetable_delete()
    {
        $id = (int) $this->get('id');

        // Validate the id.
        if ($id <= 0)
        {
            // Set the response and exit
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }

        // $this->some_model->delete_something($id);
        $message = [
            'id' => $id,
            'message' => 'Deleted the resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }


}

/* End of file Api.php */
/* Location: .//opt/lampp/htdocs/project/app/controllers/Api.php */